index:
    path:     /
    defaults: { _controller: PregunteMePresentacionBundle:Web:index }

inscripcion:
    path:     /inscripcion
    defaults: { _controller: PregunteMePresentacionBundle:Web:inscripcion }

evaluacion:
    path:     /evaluacion
    defaults: { _controller: PregunteMePresentacionBundle:Web:evaluacion }

resultados:
    path:     /resultados
    defaults: { _controller: PregunteMePresentacionBundle:Web:resultados }
    
salir:
    path:     /salir
    defaults: { _controller: PregunteMePresentacionBundle:Web:salir }
    
formulario:
    path:     /formulario
    defaults: { _controller: PregunteMePresentacionBundle:Formulario:index }
        
dimension:
    path:     /dimension
    defaults: { _controller: PregunteMePresentacionBundle:Formulario:dimension }

seleccion_modulo:
    path:     /seleccionModulo
    defaults: { _controller: PregunteMePresentacionBundle:Web:seleccionModulo }

login:
    pattern: /login
    defaults: { _controller: PregunteMePresentacionBundle:Web:login }

login_check:
    path:   /login_check

logout:
    pattern: /logout
    defaults: { _controller: PregunteMePresentacionBundle:Web:logout }
registro:
    pattern: /registro
    defaults: { _controller: PregunteMePresentacionBundle:Web:registro }

