PregunteMe\AdministracionBundle\Entity\CasoEstudio:
    type: entity
    table: null
    repositoryClass: PregunteMe\AdministracionBundle\Entity\CasoEstudioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        institucion:
            type: string
            length: 255
        programa:
            type: string
            length: 255
        nombre:
            type: string
            length: 255
        correo:
            type: string
            length: 255
        fecha:
            type: datetime
        nombreObjeto:
            type: string
            length: 255
    manyToMany:
        respuestas:
            targetEntity: Respuesta
            inversedBy: casosEstudio
    lifecycleCallbacks: {  }
