PregunteMe\AdministracionBundle\Entity\Categoria:
    type: entity
    table: null
    repositoryClass: PregunteMe\AdministracionBundle\Entity\CategoriaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        descripcion:
            type: text
        justificacion:
            type: text
        peso:
            type: float
    manyToOne:
        dimension:
            targetEntity: Dimension
            inversedBy: categorias
    oneToMany:
        indicadores:
            targetEntity: Indicador
            mappedBy: categoria           
    lifecycleCallbacks: {  }
