PregunteMe\AdministracionBundle\Entity\Usuario:
    type: entity
    table: null
    repositoryClass: PregunteMe\AdministracionBundle\Entity\UsuarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        user:
            type: string
            length: 255
        pass:
            type: string
            length: 255
        email:
            type: string
            length: 255
        fechaRegistro:
            type: datetime
    oneToMany:
        casosEstudio:
            targetEntity: CasoEstudio
            mappedBy: usuario      
    lifecycleCallbacks: {  }
