security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        PregunteMe\AdministracionBundle\Entity\Usuario:
            algorithm: md5
            iterations: 4521
            encode_as_base64: true
    providers:
        chain_provider:
            chain:
                providers: [user_db]
        user_db:
            entity: { class: PregunteMe\AdministracionBundle\Entity\Usuario, property: user }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /
                invalidate_session: false
