<?php

namespace PregunteMe\AdministracionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DimensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DimensionRepository extends EntityRepository
{
}
