<?php

namespace PregunteMe\AdministracionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IndicadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicadorRepository extends EntityRepository
{
}
