<?php

namespace PregunteMe\AdministracionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuloRepository extends EntityRepository
{
}
