admin_respuesta:
    path:     /
    defaults: { _controller: "PregunteMeAdministracionBundle:Respuesta:index" }

admin_respuesta_show:
    path:     /{id}/show
    defaults: { _controller: "PregunteMeAdministracionBundle:Respuesta:show" }

admin_respuesta_new:
    path:     /new
    defaults: { _controller: "PregunteMeAdministracionBundle:Respuesta:new" }

admin_respuesta_create:
    path:     /create
    defaults: { _controller: "PregunteMeAdministracionBundle:Respuesta:create" }
    requirements: { _method: post }

admin_respuesta_edit:
    path:     /{id}/edit
    defaults: { _controller: "PregunteMeAdministracionBundle:Respuesta:edit" }

admin_respuesta_update:
    path:     /{id}/update
    defaults: { _controller: "PregunteMeAdministracionBundle:Respuesta:update" }
    requirements: { _method: post|put }

admin_respuesta_delete:
    path:     /{id}/delete
    defaults: { _controller: "PregunteMeAdministracionBundle:Respuesta:delete" }
    requirements: { _method: post|delete }
